{% set name = "disk-objectstore" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-','_') }}-{{ version }}.tar.gz
  sha256: f0653574990402fd91a5d91b0a64ea541fb349baed02edfe7e90cf7bf3d5270c

build:
  number: 0
  entry_points:
    - dostore = disk_objectstore.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - python >={{ python_min }}
    - click
    - sqlalchemy >=1.4.22

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - disk_objectstore
    - disk_objectstore.examples
  commands:
    - pip check
    - dostore --help

about:
  home: http://github.com/aiidateam/disk-objectstore
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An implementation of an efficient object store writing directly into a disk folder

extra:
  recipe-maintainers:
    - chrisjsewell
    - sphuber
    - khsrali
    - giovannipizzi
